### Get for token

GET http://localhost:5220/api/auth/gen

### Use token

GET http://localhost:5220/api/auth/check
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYmYiOjE3NTE5MDg1ODUsImV4cCI6MTc1MTkxMjI0NSwiaWF0IjoxNzUxOTA4NjQ1LCJpc3MiOiJsb2NhbGhvc3Q6NTIyMCIsImF1ZCI6ImxvY2FsaG9zdDo1MjIwIn0.oExFjfJCz_CN4xt3LEUZLe2bpv9aXPTvtVh86QvhYDE
