### Get for token

GET http://localhost:5220/api/auth/gen

### Use token

GET http://localhost:5220/api/auth/check
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYmYiOjE3NTE4OTk3NjcsImV4cCI6MTc1MTkwMzQyNywiaWF0IjoxNzUxODk5ODI3LCJpc3MiOiJsb2NhbGhvc3Q6NTIyMCIsImF1ZCI6ImxvY2FsaG9zdDo1MjIwIn0.aKw2QEZxk5ZOJFp7ekkrInWq-Nud0zQd_xacCzT7Wo0